### ISSUE TITLE
Figure out how to add blog summaries

### ISSUE THREAD

**Issue by TheBeachMaster** [Tambua-WomenInTech-Blog/womenintechblogdev#2]
For some unknown reason, blog summaries do not show up

For context > https://gohugo.io/content-management/summaries/

**Comment by JosephineAkello** [comment]
@TheBeachMaster could you please expound more on what you mean by blog summaries not showing up?

**Comment by TheBeachMaster** [comment]
![Screenshot_20220311_230728](https://user-images.githubusercontent.com/9129843/157954482-c74e7563-574a-4a8d-b75f-53fdd475952b.png)

**Comment by JosephineAkello** [comment]
@TheBeachMaster Is this still an issue, I see its showing ama?
