### ISSUE TITLE
Contact page showing blank form

### ISSUE THREAD

**Issue by JosephineAkello** [Tambua-WomenInTech-Blog/womenintechblogdev#24]
Contact page form is showing blank, difficult to tell what needs to be filled, also the button doesnt show any label
<img width="1228" alt="Screenshot 2022-05-11 at 16 07 32" src="https://user-images.githubusercontent.com/39112051/167857519-a41359bc-7fbf-40e2-9910-3095ffeafa66.png">

**Comment by TheBeachMaster** [comment]
See basic configuration here > https://docs.gethugothemes.com/bookworm/basic-configuration/

Create a https://formspree.io/ account, then create a contact form action

Then paste it inside `config.toml` under `contact_form_action` key

**Comment by JosephineAkello** [comment]
@TheBeachMaster Thank you lemme check 😃
